name: e_card
description: Business cards sharable with NFC

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  mask_text_input_formatter: ^1.1.0
  nfc_in_flutter: ^2.0.5
  provider: ^4.3.2+2
  qr_flutter: ^3.2.0
  sqflite: ^1.3.1+1
  vcard: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
